# This is a basic workflow to help you get started with Actions
#
name: Build Artifact, Build & Push Image

on: workflow_dispatch
#on:
#  push:
#    branches: [ main ]
#    paths-ignore: 
#      - kubernetes/**
#      - .github/workflows/**
#  pull_request:
#    branches: [ main ]
#    paths-ignore:
#      - kubernetes/**
#      - .github/workflows/**

env:
  # TODO: Change registry URL if not using Docker Hub
  CONTAINER_REGISTRY_URL: https://registry.hub.docker.com
  # TODO: Change Registry USERID to your userid
  REGISTRY_USERID: omearaj
  #TODO: Only change if you already have a spring-petclinic you want to keep. 
  IMAGE_NAME: admin-server

jobs:
#  snyk_vulnerability_check:
#    
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      
#      - name: Run Snyk test
#        uses: snyk/actions/maven@master
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
#        with:
#          command: test
#      
#      - name: Run Snyk monitor
#        uses: snyk/actions/maven@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
#        with:
#          command: monitor
#          args: --severity-threshold=high

  build_mvn_aritfact:

    #needs: snyk_vulnerability_check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Build with Maven
      run: |
       mvn -Pk8s -pl spring-petclinic-admin-server/ spring-boot:build-image -DREPOSITORY_PREFIX=${{ env.REGISTRY_USERID }}
       echo "${{ secrets.DOCKER_KEY }}" | docker login ${{ env.CONTAINER_REGISTRY_URL }} -u ${{ env.REGISTRY_USERID }} --password-stdin
       docker images
       docker push docker.io/omearaj/admin-server:latest
      
#    - uses: actions/checkout@master
#    - name: Publish to Registry
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#       name: docker.io/omearaj/admin-server:latest
#       username: ${{ env.REGISTRY_USERID }}
#       password: ${{ secrets.DOCKER_KEY }}
       #default_branch: main
    
        
